name: topsters
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_gradients: ^1.0.0+3
  flutter_slidable: ^0.5.4
  get_it: ^5.0.6
  google_fonts: ^1.1.2
  http: ^0.12.1
  localstorage: ^3.0.2+5
  multi_select_item: ^1.0.3
  neuomorphic_container: ^2.0.3
  provider: ^4.3.1
  rxdart: ^0.25.0
  shared_preferences: ^0.5.7+3
  sliding_up_panel: ^1.0.2
  slimy_card: ^1.0.4
  smart_select: ^4.3.2
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.2.9
  lint: ^1.0.0
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/topsters_logo.png
