name: topsters
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  equatable: ^2.0.0
  flashy_tab_bar: ^0.0.3
  flutter_animated_button: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_gradients: ^1.0.0+3
  flutter_overlay_loader: ^0.1.1
  flutter_slidable: ^0.5.4
  flutter_spinbox: ^0.4.0
  flutter_spinkit: ^5.0.0
  flutter_touch_spin: ^1.0.1
  get_it: ^5.0.6
  google_fonts: ^1.1.2
  http: ^0.12.1
  lite_rolling_switch: ^0.1.1
  localstorage: ^3.0.2+5
  motion_tab_bar: ^0.1.5
  multi_select_item: ^1.0.3
  neuomorphic_container: ^2.0.3
  number_inc_dec: ^0.6.6
  number_selection: ^0.0.1
  numberpicker: ^2.0.1
  provider: ^5.0.0
  rxdart: ^0.25.0
  scroll_to_index: ^2.0.0
  shared_preferences: ^0.5.7+3
  sliding_up_panel: ^1.0.2
  slimy_card: ^1.0.4
  smart_select: ^4.3.2
  tab_indicator_styler: ^1.0.0
  toggle_switch: ^0.1.9
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.2.9
  lint: ^1.0.0
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/topsters_logo.png
    - assets/grid.png
    - assets/left-bars.png
    - assets/t1.png
    - assets/t2.png
    - assets/100tiles.png
    - assets/40tiles.png
    - assets/100tilesname.png
    - assets/40tilesname.png
    - assets/42tilesname.png
